export const BASE_URL = "https://github.integrations.asana.plus/custom/v1";
export const ACTION_URL = "actions/comment";
export const RETRIES = 3;
export const RETRY_DELAY = 1000;
export const BASE_ASANA_URL = "https://app.asana.com/api/1.0";
export const TASKS_URL = "/tasks/";
export const SECTIONS_URL = "/sections/";
export const SUBTASKS_URL =
  "/subtasks?opt_fields=completed,resource_subtype,assignee";
export const ADD_FOLLOWERS_URL = "/addFollowers";
export const ADD_TASK_URL = "/addTask";
export const BASE_GITHUB_URL = "https://api.github.com/";
export const REPOS_URL = "/repos/";
export const PULLS_URL = "/pulls/";
export const REVIEWS_URL = "/reviews";
export const STORIES_URL = "/stories";
